<script setup lang="ts">
definePageMeta({ middleware: 'admin', layout: 'admin' })
const route = useRoute()
const { books, updateBook } = useCatalog()
const { data, activeLoans, overdueLoans, addMember, createLoan, returnLoan, addFine, payFine, updateSettings } = useAdminLibrary()
const { push: toast } = useToast()
const section = computed(() => String(route.params.section || '').toLowerCase())
const labels: Record<string, string> = { members: 'Members', circulation: 'Circulation', fines: 'Fines', reports: 'Reports', settings: 'Settings' }
const title = computed(() => labels[section.value])
const memberForm = reactive({ name: '', email: '', role: 'Student' as 'Student' | 'Teacher' })
const loanForm = reactive({ memberId: 0, bookId: 0 })
const fineForm = reactive({ memberId: 0, amount: 0, reason: '' })
const settingsForm = reactive({ ...data.value.settings })
const search = ref('')
const memberFor = (id: number) => data.value.members.find((item) => item.id === id)
const bookFor = (id: number) => books.value.find((item) => item.id === id)
const filteredMembers = computed(() => data.value.members.filter((member) => `${member.name} ${member.email}`.toLowerCase().includes(search.value.toLowerCase())))
const outstandingFines = computed(() => data.value.fines.filter((fine) => !fine.paid))
const availableBooks = computed(() => books.value.filter((book) => book.availability.digitalCopies > book.availability.checkedOut))
const totalFineAmount = computed(() => outstandingFines.value.reduce((sum, fine) => sum + fine.amount, 0))
function createMember() { if (!memberForm.name.trim() || !memberForm.email.trim()) return toast('Enter a member name and email.', 'error'); addMember({ ...memberForm, name: memberForm.name.trim(), email: memberForm.email.trim() }); memberForm.name = ''; memberForm.email = ''; toast('Member added.') }
function issueLoan() { const book = bookFor(loanForm.bookId); if (!loanForm.memberId || !book) return toast('Choose both a member and a book.', 'error'); if (!createLoan(loanForm.memberId, book.id)) return toast('This member already has that title.', 'error'); updateBook(book.id, { availability: { ...book.availability, checkedOut: book.availability.checkedOut + 1 } }); loanForm.memberId = 0; loanForm.bookId = 0; toast('Loan issued.') }
function finishLoan(id: number) { const loan = returnLoan(id); if (!loan) return; const book = bookFor(loan.bookId); if (book) updateBook(book.id, { availability: { ...book.availability, checkedOut: Math.max(0, book.availability.checkedOut - 1) } }); toast('Book returned.') }
function createFine() { if (!addFine(fineForm.memberId, Number(fineForm.amount), fineForm.reason)) return toast('Choose a member and enter a fine amount.', 'error'); fineForm.memberId = 0; fineForm.amount = 0; fineForm.reason = ''; toast('Fine added to the member account.') }
function saveSettings() { updateSettings({ ...settingsForm, loanDays: Number(settingsForm.loanDays), finePerDay: Number(settingsForm.finePerDay) }); toast('Library settings saved.') }
function downloadReport() { const rows = [['Metric', 'Value'], ['Members', String(data.value.members.length)], ['Active loans', String(activeLoans.value.length)], ['Overdue loans', String(overdueLoans.value.length)], ['Outstanding fines', `$${totalFineAmount.value.toFixed(2)}`], ['Catalog titles', String(books.value.length)]]; const url = URL.createObjectURL(new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'etec-library-report.csv'; link.click(); URL.revokeObjectURL(url); toast('Report downloaded.') }
if (!title.value) await navigateTo('/admin')
</script>

<template>
  <div v-if="title" class="mx-auto max-w-7xl space-y-6">
    <header><p class="text-sm text-slate-500">Library management</p><h1 class="mt-1 text-2xl font-bold text-slate-900">{{ title }}</h1></header>

    <template v-if="section === 'members'"><section class="grid gap-6 lg:grid-cols-[1fr_1.5fr]"><form class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" @submit.prevent="createMember"><h2 class="font-semibold text-slate-900">Add member</h2><div class="mt-4 space-y-3"><input v-model="memberForm.name" required placeholder="Full name" class="field" /><input v-model="memberForm.email" required type="email" placeholder="Email address" class="field" /><select v-model="memberForm.role" class="field"><option>Student</option><option>Teacher</option></select><button class="primary">Add member</button></div></form><section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><input v-model="search" type="search" placeholder="Search members..." class="field" /></div><div class="divide-y divide-slate-100"><div v-for="member in filteredMembers" :key="member.id" class="flex items-center gap-3 p-4"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 font-semibold text-blue-600">{{ member.name[0] }}</span><div class="min-w-0 flex-1"><p class="font-medium text-slate-800">{{ member.name }}</p><p class="text-xs text-slate-500">{{ member.email }} · {{ member.role }}</p></div><span class="text-xs text-slate-400">{{ activeLoans.filter(loan => loan.memberId === member.id).length }} loans</span></div></div></section></section></template>

    <template v-else-if="section === 'circulation'"><section class="grid gap-6 lg:grid-cols-[1fr_1.5fr]"><form class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" @submit.prevent="issueLoan"><h2 class="font-semibold text-slate-900">Issue a loan</h2><p class="mt-1 text-xs text-slate-500">Due in {{ data.settings.loanDays }} days.</p><div class="mt-4 space-y-3"><select v-model.number="loanForm.memberId" class="field"><option :value="0">Select member</option><option v-for="member in data.members" :key="member.id" :value="member.id">{{ member.name }}</option></select><select v-model.number="loanForm.bookId" class="field"><option :value="0">Select available book</option><option v-for="book in availableBooks" :key="book.id" :value="book.id">{{ book.title }}</option></select><button class="primary">Issue loan</button></div></form><section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-semibold text-slate-900">Active loans</h2></div><div v-if="activeLoans.length" class="divide-y divide-slate-100"><div v-for="loan in activeLoans" :key="loan.id" class="flex items-center gap-3 p-4"><div class="min-w-0 flex-1"><p class="font-medium text-slate-800">{{ bookFor(loan.bookId)?.title || 'Removed title' }}</p><p class="text-xs text-slate-500">{{ memberFor(loan.memberId)?.name }} · Due {{ loan.dueOn }}</p></div><span v-if="loan.dueOn < new Date().toISOString().slice(0, 10)" class="text-xs font-semibold text-red-500">Overdue</span><button type="button" class="secondary" @click="finishLoan(loan.id)">Return</button></div></div><p v-else class="p-8 text-center text-sm text-slate-500">No active loans.</p></section></section></template>

    <template v-else-if="section === 'fines'"><section class="grid gap-4 sm:grid-cols-3"><div class="card"><p>Outstanding</p><strong>{{ outstandingFines.length }}</strong></div><div class="card"><p>Amount due</p><strong>${{ totalFineAmount.toFixed(2) }}</strong></div><div class="card"><p>Paid fines</p><strong>{{ data.fines.filter(fine => fine.paid).length }}</strong></div></section><section class="grid gap-6 lg:grid-cols-[.8fr_1.5fr]"><form class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" @submit.prevent="createFine"><h2 class="font-semibold text-slate-900">Add a fine</h2><p class="mt-1 text-xs text-slate-500">Use this for damaged, lost, or other library charges.</p><div class="mt-4 space-y-3"><select v-model.number="fineForm.memberId" class="field"><option :value="0">Select member</option><option v-for="member in data.members" :key="member.id" :value="member.id">{{ member.name }}</option></select><input v-model.number="fineForm.amount" min="0.01" step="0.01" type="number" placeholder="Amount (USD)" class="field" /><input v-model="fineForm.reason" placeholder="Reason, e.g. damaged book" class="field" /><button class="primary">Add fine</button></div></form><section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="font-semibold text-slate-900">Fine register</h2></div><div v-if="data.fines.length" class="divide-y divide-slate-100"><div v-for="fine in data.fines" :key="fine.id" class="flex items-center gap-3 p-4"><span class="flex h-9 w-9 items-center justify-center rounded-full" :class="fine.paid ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600'">$</span><div class="min-w-0 flex-1"><p class="font-medium text-slate-800">{{ memberFor(fine.memberId)?.name || 'Former member' }}</p><p class="truncate text-xs text-slate-500">{{ fine.reason || 'Library charge' }}<span v-if="fine.bookId"> · {{ bookFor(fine.bookId)?.title }}</span></p><p class="mt-0.5 text-[11px] text-slate-400">Created {{ fine.createdOn }}<span v-if="fine.paidOn"> · Paid {{ fine.paidOn }}</span></p></div><span class="font-semibold text-slate-800">${{ fine.amount.toFixed(2) }}</span><button v-if="!fine.paid" type="button" class="secondary" @click="payFine(fine.id)">Mark paid</button><span v-else class="text-xs font-semibold text-emerald-600">Paid</span></div></div><p v-else class="p-8 text-center text-sm text-slate-500">Fines are created automatically when an overdue book is returned, or you can add one manually.</p></section></section></template>

    <template v-else-if="section === 'reports'"><section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="item in [{ label: 'Members', value: data.members.length }, { label: 'Active loans', value: activeLoans.length }, { label: 'Overdue', value: overdueLoans.length }, { label: 'Available books', value: availableBooks.length }]" :key="item.label" class="card"><p>{{ item.label }}</p><strong>{{ item.value }}</strong></div></section><section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold text-slate-900">Library summary</h2><p class="mt-2 max-w-xl text-sm leading-6 text-slate-500">Download a CSV summary based on the current members, loans, fines, and catalog records.</p><button type="button" class="primary mt-5" @click="downloadReport">Download CSV report</button></section></template>

    <template v-else-if="section === 'settings'"><form class="max-w-2xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm" @submit.prevent="saveSettings"><h2 class="font-semibold text-slate-900">Library preferences</h2><div class="mt-5 space-y-4"><label class="block text-sm font-medium">Library name<input v-model="settingsForm.libraryName" class="field mt-1" /></label><label class="block text-sm font-medium">Default loan period (days)<input v-model.number="settingsForm.loanDays" min="1" type="number" class="field mt-1" /></label><label class="block text-sm font-medium">Late fee per day (USD)<input v-model.number="settingsForm.finePerDay" min="0" step="0.25" type="number" class="field mt-1" /></label><button class="primary">Save settings</button></div></form></template>
  </div>
</template>

<style scoped>
.field { @apply w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100; }
.primary { @apply rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700; }
.secondary { @apply rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50; }
.card { @apply rounded-xl border border-slate-200 bg-white p-5 shadow-sm; }
.card p { @apply text-sm text-slate-500; }.card strong { @apply mt-3 block text-3xl text-slate-900; }
</style>
